TEclassification: run2.consensus-classification.3cols.tab

#run1.consensus-classification.3cols.tab

species:
  Orestias_ascotanensis: Orestias_ascotanensis.genome.fasta.cat.gz
  Orestias_chungarensis: Orestias_chungarensis.genome.fasta.cat.gz
  Orestias_gloriae: Orestias_gloriae.genome.fasta.cat.gz
  Orestias_laucaensis: Orestias_laucaensis.genome.fasta.cat.gz
  Anableps_anableps: Anableps_anableps.genome.fasta.cat.gz
  Cyprinodon_variegatus: Cyprinodon_variegatus.genome.fasta.cat.gz
