species:
  - Austrolebias_charrua
  - Nematolebias_whitei
  - Cynopoecilus_melanotaenia
  - Austrofundulus_limnaeus
  - Kryptolebias_marmoratus
  - Nothobranchius_furzeri
  - Oryzias_latipes

mergePrefix: "panel_Aplocheilidae_genomeContrib"


# Genome size contribution by TEorder
ordersToConsider: "LINE,SINE,DNA,LTR,Retroposon,RC,tRNA,Unknown"
TEordersToCollapseAsOther: "tRNA,Unknown,Retroposon,RC"




# for TEsuperfams barplot
collapse_lower_than_mean_contrib: "F"
onlyCoreTEsuperfams: "T"

tree: astralBestTree.nwk.olat-added


