species:
  - Orestias_gloriae
  - Orestias_ascotanensis
  - Orestias_laucaensis
  - Orestias_chungarensis
  - Anableps_anableps
  - Cyprinodon_variegatus

mergePrefix: "panel_Cyprinodontoidei_genomeContrib"


# Genome size contribution by TEorder
ordersToConsider: "LINE,SINE,DNA,LTR,Retroposon,RC,tRNA,Unknown"
TEordersToCollapseAsOther: "tRNA,Unknown,Retroposon,RC"




# for TEsuperfams barplot
collapse_lower_than_mean_contrib: "F"
onlyCoreTEsuperfams: "T"

tree: astralBestTree.nwk 


